# Dockerfile for Arosaje project
# This file is meant to be used for development purposes only

version: '3.9'

services:
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - arosaje-network

  db:
    container_name: postgres
    image: postgres:9.6
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    networks:
      - arosaje-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
      - "9100:9100"
    volumes:
      - ./backend:/app
    networks:
      - arosaje-network

  grafana:
    container_name: grafana
    image: grafana/grafana
    # environment:
    #   - GF_AUTH_DISABLE_LOGIN_FORM=true
    #   - GF_AUTH_ANONYMOUS_ENABLED=true
    #   - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - grafana-data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - arosaje-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: on-failure
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/etc/prometheus
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - arosaje-network

volumes:
  grafana-data:
  prometheus-data:


networks:
  arosaje-network:
