# Generated by Django 4.1.6 on 2023-02-13 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_rosa_je_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='address',
        ),
        migrations.RemoveField(
            model_name='review',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 20, 59, 43, 756372)),
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 20, 59, 43, 756120)),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 20, 59, 43, 758168)),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 20, 59, 43, 756873)),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 20, 59, 43, 755583)),
        ),
        migrations.AlterField(
            model_name='botanist',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='posts', to='A_rosa_je_site.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='plant',
            field=models.ManyToManyField(blank=True, related_name='posts', to='A_rosa_je_site.plant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.URLField(blank=True),
        ),
    ]
