# Generated by Django 4.1.6 on 2023-02-13 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_rosa_je_site', '0003_alter_comment_created_at_alter_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 23, 23, 55, 797137, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 23, 23, 55, 796902, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 23, 23, 55, 798176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 23, 23, 55, 797598, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 23, 23, 55, 796328, tzinfo=datetime.timezone.utc)),
        ),
    ]
