# Generated by Django 4.1.6 on 2023-02-13 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_rosa_je_site', '0004_alter_comment_created_at_alter_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 23, 25, 2, 7958, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 23, 25, 2, 7687, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 23, 25, 2, 9172, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 23, 25, 2, 8505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 23, 25, 2, 6961, tzinfo=datetime.timezone.utc)),
        ),
    ]
